# Generated by Django 4.1.2 on 2024-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="content",
            new_name="description",
        ),
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(default="Untitled", max_length=100),
        ),
    ]
