# Generated by Django 4.1.2 on 2024-11-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_content_item_description_item_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="description",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="item",
            name="name",
        ),
    ]
